name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Evento: ${{ github.event_name }}"
          echo "Nome do Branch ${{ github.ref }}"

      - uses: actions/checkout@v4

      - name: Lista de ficheiros no repositorio
        run: |
          echo "O repositorio ${{ github.repository }} tem os seguintes ficheiros:"
          tree
